// API Service
export const SEND_REQUEST = 'SEND_REQUEST';
export const RECEIVE_RESPONSE = 'RECEIVE_RESPONSE';
export const BROADCAST_MESSAGE_UPDATE = 'BROADCAST_MESSAGE_UPDATE';

// Authentication
export const SET_AUTHENTICATED_STATUS = 'SET_AUTHENTICATED_STATUS';
export const SET_AUTHENTICATION_ERROR = 'SET_AUTHENTICATION_ERROR';
